//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGE.Cagravol.Presentation.Resources.Templates {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplateResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplateResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGE.Cagravol.Presentation.Resources.Templates.EmailTemplateResources", typeof(EmailTemplateResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h2&gt;¡Bienvenido!&lt;/h2&gt;
        ///&lt;p&gt;Acaba de ser incluido como usuario del sistema de gestión de Envíos de Artes Finales con el email {0}&lt;p&gt;
        ///&lt;p&gt;Para acceder al sistema, vaya a la p&amp;aacute;gina de &lt;a href=&quot;{1}&quot;&gt;Entrada al Sistema&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;Como nombre de usuario, utilice esta dirección de correo: &lt;strong&gt;{0}&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;Su Contraseña (Seleccione texto para ver): &lt;strong style=&quot;background-color:#000000; color:#000000&quot;&gt;{2}&lt;/strong&gt;&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;Puede modificar su Contraseña desde su perfil como usuario, una ve [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string CustomerAssigned {
            get {
                return ResourceManager.GetString("CustomerAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h2&gt;¡Bienvenido!&lt;/h2&gt;
        ///&lt;p&gt;Un espacio como usuario para usted acaba de ser reservado en el sistema de gestión de Envíos de Artes Finales con el email {0}&lt;p&gt;
        ///&lt;p&gt;Para acceder al sistema, vaya a la p&amp;aacute;gina de &lt;a href=&quot;{1}&quot;&gt;Entrada al Sistema&lt;/a&gt;, y establezca una contraseña para registrarse definitivamente (Obligatorio),&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;Puede modificar su Contraseña posteriormente, desde su perfil como usuario, una vez registrado y logueado en el sistema.&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;Gracias por utilizar nuestros servi [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string CustomerReserved {
            get {
                return ResourceManager.GetString("CustomerReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h2&gt;¡Bienvenido!&lt;/h2&gt;
        ///&lt;p&gt;Acaba de darse de alta en el sistema de gestión de Envíos de Artes Finales con el email {0}&lt;p&gt;
        ///&lt;p&gt;Para acceder al sistema, vaya a la p&amp;aacute;gina de &lt;a href=&quot;{1}&quot;&gt;Entrada al Sistema&lt;/a&gt;&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;Gracias por utilizar nuestros servicios.&lt;/p&gt;.
        /// </summary>
        public static string CustomerSignUp {
            get {
                return ResourceManager.GetString("CustomerSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;small&gt;
        ///&lt;strong&gt;ADVERTENCIA LEGAL&lt;/strong&gt;
        ///&lt;br/&gt;
        ///Le informamos, como destinatario de este mensaje, que el correo electrónico y las comunicaciones por medio de Internet no permiten asegurar ni garantizar la confidencialidad de los mensajes transmitidos, así como tampoco su integridad o su correcta recepción, por lo que el emisor no asume responsabilidad alguna por tales circunstancias. Si no consintiese en la utilización del correo electrónico o de las comunicaciones vía Internet le rogamos nos lo comuniq [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string LegalDisclaimer_Format {
            get {
                return ResourceManager.GetString("LegalDisclaimer_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [GRAFIDEC] Archivo Añadido al Sistema.
        /// </summary>
        public static string WFFileAddedSubject {
            get {
                return ResourceManager.GetString("WFFileAddedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h2&gt;Cambio en Estado de Archivo: {0} ({1})&lt;/h2&gt;
        ///&lt;p&gt;El Usuario {1} acaba de modificar el estado del archivo la denominación {0} (Nombre Original: {1}) al estado &lt;strong&gt;{6}&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;Puede ver los detalles sobre el estado de este archivo &lt;a href=&quot;{3}&quot; target=&quot;_blank&quot;&gt;aqu&amp;iacute;&lt;/a&gt;.&lt;p&gt;
        ///&lt;p&gt;NOTA: Recuerde que para ver los detalles o descargar el archivo, debe estar logueado en el sistema con su usuario (email) y contrase&amp;ntilde;a correspondientes.&lt;p&gt;
        ///&lt;p&gt;Para acceder al sistema, vaya a la p&amp;aacute;gi [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string WFFileStateChangedTo_Format {
            get {
                return ResourceManager.GetString("WFFileStateChangedTo_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [GRAFIDEC] Cambio en Estado Archivo.
        /// </summary>
        public static string WFFileStateChangeSubject {
            get {
                return ResourceManager.GetString("WFFileStateChangeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h2&gt;Nuevo Archivo en el Sistema: {0} ({1})&lt;/h2&gt;
        ///&lt;p&gt;El Usuario {2} acaba de subir el archivo con la denominación {0} (Nombre Original: {1})&lt;/p&gt;
        ///&lt;p&gt;Puede ver los detalles sobre el estado de este archivo &lt;a href=&quot;{3}&quot; target=&quot;_blank&quot;&gt;aqu&amp;iacute;&lt;/a&gt;, o puede descargar &lt;a href=&quot;{4}&quot; target=&quot;_blank&quot;&gt;desde aqu&amp;iacute;&lt;/a&gt;.&lt;p&gt;
        ///&lt;p&gt;NOTA: Recuerde que para ver los detalles o descargar el archivo, debe estar logueado en el sistema con su usuario (email) y contrase&amp;ntilde;a correspondientes.&lt;p&gt;
        ///&lt;p&gt;Para acceder al s [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string WFNewFileInPlatform_Format {
            get {
                return ResourceManager.GetString("WFNewFileInPlatform_Format", resourceCulture);
            }
        }
    }
}
