//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGE.Cagravol.Presentation.Resources.Customers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGE.Cagravol.Presentation.Resources.Customers.CustomerResources", typeof(CustomerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Código de Expositor facilitado no existe..
        /// </summary>
        public static string CustomerCodeDoesNotExist {
            get {
                return ResourceManager.GetString("CustomerCodeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Código de Expositor facilitado ya ha sido usado..
        /// </summary>
        public static string CustomerCodeHasBeenUsed {
            get {
                return ResourceManager.GetString("CustomerCodeHasBeenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró Expositor para ningún projecto activo con el usuario facilitado..
        /// </summary>
        public static string CustomerNotFoundForAnyActiveProject {
            get {
                return ResourceManager.GetString("CustomerNotFoundForAnyActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el elemento que se pretende eliminar.
        /// </summary>
        public static string ErrorItemDoesNotExist_OnDelete {
            get {
                return ResourceManager.GetString("ErrorItemDoesNotExist_OnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error y no se pudo registrar el espacio para dicho usuario. Por favor consulte con su administrador..
        /// </summary>
        public static string ErrorOnManagerAssignSpaceToUser {
            get {
                return ResourceManager.GetString("ErrorOnManagerAssignSpaceToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error y no se pudo reservar el espacio para dicho usuario. Por favor consulte con su administrador..
        /// </summary>
        public static string ErrorOnManagerReserveSpaceToUser {
            get {
                return ResourceManager.GetString("ErrorOnManagerReserveSpaceToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra ningún Espacio Disponible Reservado. Por favor, contacte con el administrador del sistema..
        /// </summary>
        public static string ErrorReservedCustomerNotValid {
            get {
                return ResourceManager.GetString("ErrorReservedCustomerNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha límite para envíos de archivos es {0}. No es posible enviar despues de dicha fecha..
        /// </summary>
        public static string IsNotPossibleToSendOutOfDate_Format {
            get {
                return ResourceManager.GetString("IsNotPossibleToSendOutOfDate_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Evento no está disponible para nuevos registros de usuarios.
        /// </summary>
        public static string ProjectIsNotAbleForRegistration {
            get {
                return ResourceManager.GetString("ProjectIsNotAbleForRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserva de Espacio como Expositor.
        /// </summary>
        public static string ReservationMailSubject {
            get {
                return ResourceManager.GetString("ReservationMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVISO: Desde la fecha {0}, enviar un archivo tiene un recargo del {1:0.00}%..
        /// </summary>
        public static string SendFileHasRecharge_Format {
            get {
                return ResourceManager.GetString("SendFileHasRecharge_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVISO: Enviar el archivo a partir del {0} tiene un recargo del {1:0.00}%. A fecha de hoy no se aplica este recargo..
        /// </summary>
        public static string SendFileWillHaveRecharge_Format {
            get {
                return ResourceManager.GetString("SendFileWillHaveRecharge_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta de Expositor.
        /// </summary>
        public static string SignUpMailSubject {
            get {
                return ResourceManager.GetString("SignUpMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las Contraseñas no coinciden..
        /// </summary>
        public static string SignUpPasswordConfirmDoesNotMatch {
            get {
                return ResourceManager.GetString("SignUpPasswordConfirmDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este espacio {0} no está disponible, ha sido bloqueado para {0}{1} ({2}).
        /// </summary>
        public static string SpaceIsNotFree_Format {
            get {
                return ResourceManager.GetString("SpaceIsNotFree_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este usuario no tiene autorización para ver el Historial/Actividad de este archivo..
        /// </summary>
        public static string UserHasNotAuthorizationForThisFileHistory {
            get {
                return ResourceManager.GetString("UserHasNotAuthorizationForThisFileHistory", resourceCulture);
            }
        }
    }
}
