//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGE.Cagravol.Presentation.Resources.Projects {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGE.Cagravol.Presentation.Resources.Projects.ProjectResources", typeof(ProjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Recargo.
        /// </summary>
        public static string ChargePercentage {
            get {
                return ResourceManager.GetString("ChargePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Código del Evento es Obligatorio.
        /// </summary>
        public static string CodeIsRequired {
            get {
                return ResourceManager.GetString("CodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio General Evento.
        /// </summary>
        public static string CustomerCommonSpace {
            get {
                return ResourceManager.GetString("CustomerCommonSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los Expositores no pueden ver el contenido de un Evento.
        /// </summary>
        public static string CustomersCannotGetProjects {
            get {
                return ResourceManager.GetString("CustomersCannotGetProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los Expositores no pueden ver el listado de Eventos.
        /// </summary>
        public static string CustomersCannotListProjects {
            get {
                return ResourceManager.GetString("CustomersCannotListProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio de Expositor.
        /// </summary>
        public static string CustomerSpace {
            get {
                return ResourceManager.GetString("CustomerSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio de Expositor {0}.
        /// </summary>
        public static string CustomerSpace_Format {
            get {
                return ResourceManager.GetString("CustomerSpace_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Final Evento.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Evento no existe..
        /// </summary>
        public static string ErrorItemDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorItemDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Evento que se desea eliminar no existe en la base de datos..
        /// </summary>
        public static string ErrorItemDoesNotExist_OnDelete {
            get {
                return ResourceManager.GetString("ErrorItemDoesNotExist_OnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió el siguiente error. Por favor, contacte con el administrador del sistema..
        /// </summary>
        public static string ErrorOnExportationContent {
            get {
                return ResourceManager.GetString("ErrorOnExportationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al Exportar Actividad.
        /// </summary>
        public static string ErrorOnExportationTitle {
            get {
                return ResourceManager.GetString("ErrorOnExportationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un Evento con ese código. Por favor, elija otro código para este evento..
        /// </summary>
        public static string ErrorProjectCodeAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorProjectCodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movimientos de Archivos.
        /// </summary>
        public static string Excel_FilesTitle {
            get {
                return ResourceManager.GetString("Excel_FilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio General Evento.
        /// </summary>
        public static string Excel_GeneralSpaceTitle {
            get {
                return ResourceManager.GetString("Excel_GeneralSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historia del Archivo.
        /// </summary>
        public static string Excel_History {
            get {
                return ResourceManager.GetString("Excel_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ( Espacio No Asignado).
        /// </summary>
        public static string Excel_NoCustomerAssigned {
            get {
                return ResourceManager.GetString("Excel_NoCustomerAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Sin Movimientos de Archivos).
        /// </summary>
        public static string Excel_NoFilesTitle {
            get {
                return ResourceManager.GetString("Excel_NoFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay historia para este archivo..
        /// </summary>
        public static string Excel_NoHistory {
            get {
                return ResourceManager.GetString("Excel_NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXPOSITORES.
        /// </summary>
        public static string Excel_StandsTitle {
            get {
                return ResourceManager.GetString("Excel_StandsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El % de Recargo Extra debe tener formato numérico decimal. Use el punto (.) como serparador de decimales..
        /// </summary>
        public static string extraChargePercentageShoudBeAPercentage {
            get {
                return ResourceManager.GetString("extraChargePercentageShoudBeAPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Fecha de Final del Evento es Obligatoria.
        /// </summary>
        public static string FinishDateIsRequired {
            get {
                return ResourceManager.GetString("FinishDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Límite Envíos.
        /// </summary>
        public static string LimitDate {
            get {
                return ResourceManager.GetString("LimitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Fecha de Límite de Envío es Obligatoria.
        /// </summary>
        public static string LimitForSendingDateIsRequired {
            get {
                return ResourceManager.GetString("LimitForSendingDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Evento.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Nombre del Evento es Obligatorio.
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Límite Envío Sin Recargo.
        /// </summary>
        public static string NoChargeLimitDate {
            get {
                return ResourceManager.GetString("NoChargeLimitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Evento.
        /// </summary>
        public static string ProjectCode {
            get {
                return ResourceManager.GetString("ProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio Evento.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Fecha de Cominezo del Evento es Obligatoria.
        /// </summary>
        public static string StartDateIsRequired {
            get {
                return ResourceManager.GetString("StartDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº Expositores.
        /// </summary>
        public static string TotalStands {
            get {
                return ResourceManager.GetString("TotalStands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Nº Total de Expositores es Obligatorio.
        /// </summary>
        public static string TotalStandsIsRequired {
            get {
                return ResourceManager.GetString("TotalStandsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario no posee privilegios suficientes en este Evento para realizar esta acción..
        /// </summary>
        public static string UserHasNotEnoughPrivilegesOnThisProjectForThisAction {
            get {
                return ResourceManager.GetString("UserHasNotEnoughPrivilegesOnThisProjectForThisAction", resourceCulture);
            }
        }
    }
}
