//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGE.Cagravol.Presentation.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGE.Cagravol.Presentation.Resources.Common.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadido.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración Android.
        /// </summary>
        public static string AndroidConfigurationSection {
            get {
                return ResourceManager.GetString("AndroidConfigurationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave Api para Notificaciones Push en Android.
        /// </summary>
        public static string AndroidPushNotificationsApiKeyDescription {
            get {
                return ResourceManager.GetString("AndroidPushNotificationsApiKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string AndroidTitle {
            get {
                return ResourceManager.GetString("AndroidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esquema de Colores de la App.
        /// </summary>
        public static string AppColorSchema {
            get {
                return ResourceManager.GetString("AppColorSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagenes disponibles.
        /// </summary>
        public static string AvailableImagesTitle {
            get {
                return ResourceManager.GetString("AvailableImagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos disponibles.
        /// </summary>
        public static string AvailableVideosTitle {
            get {
                return ResourceManager.GetString("AvailableVideosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grosor Borde.
        /// </summary>
        public static string BorderSize {
            get {
                return ResourceManager.GetString("BorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barra Opciones Inferior.
        /// </summary>
        public static string BottomToolbar {
            get {
                return ResourceManager.GetString("BottomToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Fondo Barra.
        /// </summary>
        public static string BottomToolbarBackgroundColor {
            get {
                return ResourceManager.GetString("BottomToolbarBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Texto/Iconos Opciones.
        /// </summary>
        public static string BottomToolbarForegroundColor {
            get {
                return ResourceManager.GetString("BottomToolbarForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En algunas secciones, los elementos de dicha sección tienen varias posibilidades, como por ejemplo, indicar &apos;Me Gusta&apos;, contactar con usted telefónicamente, etc. Este menú consta de un fondo, y las opciones están formadas por botones con texto e icono. Aquí puede establecer el color de fondo de dicha barra de opciones (que siempre aparecerá en la zona inferior), y del texto e iconos de los botones de opción.
        /// </summary>
        public static string BottomToolbarNote {
            get {
                return ResourceManager.GetString("BottomToolbarNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Comprobado!.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.I.F..
        /// </summary>
        public static string CIF {
            get {
                return ResourceManager.GetString("CIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar filtro.
        /// </summary>
        public static string CleanFilter {
            get {
                return ResourceManager.GetString("CleanFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrado.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color fondo.
        /// </summary>
        public static string ColorBackground {
            get {
                return ResourceManager.GetString("ColorBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color bordes.
        /// </summary>
        public static string ColorBorders {
            get {
                return ResourceManager.GetString("ColorBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color fondo de contenido.
        /// </summary>
        public static string ColorContentBackground {
            get {
                return ResourceManager.GetString("ColorContentBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color enlaces.
        /// </summary>
        public static string ColorLinks {
            get {
                return ResourceManager.GetString("ColorLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color texto principal.
        /// </summary>
        public static string ColorMainText {
            get {
                return ResourceManager.GetString("ColorMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color texto secundario.
        /// </summary>
        public static string ColorMinorText {
            get {
                return ResourceManager.GetString("ColorMinorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color títulos.
        /// </summary>
        public static string ColorTitle {
            get {
                return ResourceManager.GetString("ColorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color fondo Barra de Título.
        /// </summary>
        public static string ColorTitleBackground {
            get {
                return ResourceManager.GetString("ColorTitleBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Mostrando {0} a {1} de {2} registros).
        /// </summary>
        public static string CounterPhrase {
            get {
                return ResourceManager.GetString("CounterPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminos y Condiciones uso Cupón - Texto por defecto.
        /// </summary>
        public static string CouponTermsAndConditionDefaultTitle {
            get {
                return ResourceManager.GetString("CouponTermsAndConditionDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Build de la app para la versión presente.
        /// </summary>
        public static string CUSTOMER_APP_RELEASE_NUMBER {
            get {
                return ResourceManager.GetString("CUSTOMER_APP_RELEASE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave de Paso necesaria para obtener Datos del Perfil del cliente a través de servicio web.
        /// </summary>
        public static string CustomerDataPassKeyDescription {
            get {
                return ResourceManager.GetString("CustomerDataPassKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/yyyy.
        /// </summary>
        public static string DateTimeBinder_DateTimeDayMonthYearHourMinuteFormat {
            get {
                return ResourceManager.GetString("DateTimeBinder_DateTimeDayMonthYearHourMinuteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm.
        /// </summary>
        public static string DateTimeBinder_DateTimeDayMonthYearHourMinuteSecondsFormat {
            get {
                return ResourceManager.GetString("DateTimeBinder_DateTimeDayMonthYearHourMinuteSecondsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string DateTimeBinder_DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeBinder_DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm:ss.
        /// </summary>
        public static string DateTimeBinder_DateTimeMonthYearFormat {
            get {
                return ResourceManager.GetString("DateTimeBinder_DateTimeMonthYearFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string DateTimePickerCloseButton {
            get {
                return ResourceManager.GetString("DateTimePickerCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoy/Ahora.
        /// </summary>
        public static string DateTimePickerCurrentButton {
            get {
                return ResourceManager.GetString("DateTimePickerCurrentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;Lu&quot;,&quot;Ma&quot;,&quot;Mi&quot;,&quot;Ju&quot;,&quot;Vi&quot;,&quot;Sa&quot;,&quot;Do&quot;,&quot;Lu&quot;].
        /// </summary>
        public static string DateTimePickerDayNamesShort {
            get {
                return ResourceManager.GetString("DateTimePickerDayNamesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora (0-23).
        /// </summary>
        public static string DateTimePickerHourText {
            get {
                return ResourceManager.GetString("DateTimePickerHourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutos (0-59).
        /// </summary>
        public static string DateTimePickerMinuteText {
            get {
                return ResourceManager.GetString("DateTimePickerMinuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ &quot;Ene&quot;, &quot;Feb&quot;, &quot;Mar&quot;, &quot;Abr&quot;, &quot;May&quot;, &quot;Jun&quot;, &quot;Jul&quot;, &quot;Ago&quot;, &quot;Sep&quot;, &quot;Oct&quot;, &quot;Nov&quot;, &quot;Dic&quot; ].
        /// </summary>
        public static string DateTimePickerMonthNamesShort {
            get {
                return ResourceManager.GetString("DateTimePickerMonthNamesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        public static string DateTimePickerTimeFormat {
            get {
                return ResourceManager.GetString("DateTimePickerTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario.
        /// </summary>
        public static string DateTimePickerTimeText {
            get {
                return ResourceManager.GetString("DateTimePickerTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Día.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días (por defecto) que la oferta permanece activa desde el día en que se crea..
        /// </summary>
        public static string DEFAULT_OFFER_ACTIVE_PERIOD {
            get {
                return ResourceManager.GetString("DEFAULT_OFFER_ACTIVE_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por defecto, en ofertas, mostrar botón &apos;Contactar&apos;.
        /// </summary>
        public static string DEFAULT_OFFER_SHOW_BUTTON_CONTACT {
            get {
                return ResourceManager.GetString("DEFAULT_OFFER_SHOW_BUTTON_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por defecto, en ofertas, mostrar botón &apos;Me Gusta&apos;.
        /// </summary>
        public static string DEFAULT_OFFER_SHOW_BUTTON_LIKE {
            get {
                return ResourceManager.GetString("DEFAULT_OFFER_SHOW_BUTTON_LIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por defecto, en ofertas, mostrar botón &apos;Reservar&apos;.
        /// </summary>
        public static string DEFAULT_OFFER_SHOW_BUTTON_RESERVATION {
            get {
                return ResourceManager.GetString("DEFAULT_OFFER_SHOW_BUTTON_RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por defecto, en ofertas, mostrar botón &apos;Compartir&apos;.
        /// </summary>
        public static string DEFAULT_OFFER_SHOW_BUTTON_SHARE {
            get {
                return ResourceManager.GetString("DEFAULT_OFFER_SHOW_BUTTON_SHARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminado.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Eliminar.
        /// </summary>
        public static string DeletedError {
            get {
                return ResourceManager.GetString("DeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro ha sido eliminado con éxito..
        /// </summary>
        public static string DeleteResultSuccessful {
            get {
                return ResourceManager.GetString("DeleteResultSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar {0}.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseleccionar Todos.
        /// </summary>
        public static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escritorio.
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivos.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden.
        /// </summary>
        public static string DisplayOrderTitle {
            get {
                return ResourceManager.GetString("DisplayOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar.
        /// </summary>
        public static string DoFilter {
            get {
                return ResourceManager.GetString("DoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Modificar.
        /// </summary>
        public static string EditError {
            get {
                return ResourceManager.GetString("EditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro ha sido modificado con éxito..
        /// </summary>
        public static string EditResultSuccess {
            get {
                return ResourceManager.GetString("EditResultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha guadrado con éxito. No se han enviado notificaciones a los dispositivos..
        /// </summary>
        public static string ElementSavedNotPushNotificationDoneSuccessfully {
            get {
                return ResourceManager.GetString("ElementSavedNotPushNotificationDoneSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Sin Imagen).
        /// </summary>
        public static string EmptyImageName {
            get {
                return ResourceManager.GetString("EmptyImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Registrado.
        /// </summary>
        public static string FinalUser {
            get {
                return ResourceManager.GetString("FinalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Usuario Registrado.
        /// </summary>
        public static string FinalUserEmail {
            get {
                return ResourceManager.GetString("FinalUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Usuario Registrado.
        /// </summary>
        public static string FinalUserName {
            get {
                return ResourceManager.GetString("FinalUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Usuario Registrado.
        /// </summary>
        public static string FinalUserPhoneNumber {
            get {
                return ResourceManager.GetString("FinalUserPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franquicia.
        /// </summary>
        public static string Franchise {
            get {
                return ResourceManager.GetString("Franchise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios Futuribles.
        /// </summary>
        public static string FutureFinalUserCustomer {
            get {
                return ResourceManager.GetString("FutureFinalUserCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido seleccionado.
        /// </summary>
        public static string HasNotBeenSelected {
            get {
                return ResourceManager.GetString("HasNotBeenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Es Usuario Registrado?.
        /// </summary>
        public static string HasUserInfo {
            get {
                return ResourceManager.GetString("HasUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barra Título Superior.
        /// </summary>
        public static string HeaderBar {
            get {
                return ResourceManager.GetString("HeaderBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Fondo Barra.
        /// </summary>
        public static string HeaderBarBackgroundColor {
            get {
                return ResourceManager.GetString("HeaderBarBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Icono Menu.
        /// </summary>
        public static string HeaderBarForegroundColor {
            get {
                return ResourceManager.GetString("HeaderBarForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cabecera se compone del Logo de Cabecera y el icono que despliega el menú de la App. El Logo de cabecera lo puede establecer en el apartado Administración/Imagen Corporativa (Si tiene los permisos adecuados. Si no los tiene, pida a su Manager que lo realice). Tambien puede indicar el color de Fondo de dicha barra, y el color del Icono de despliegue de menú..
        /// </summary>
        public static string HeaderBarNote {
            get {
                return ResourceManager.GetString("HeaderBarNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Hola {0}!.
        /// </summary>
        public static string HelloUser {
            get {
                return ResourceManager.GetString("HelloUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenido.
        /// </summary>
        public static string HtmlContent {
            get {
                return ResourceManager.GetString("HtmlContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galería de Imágenes.
        /// </summary>
        public static string ImageGallery {
            get {
                return ResourceManager.GetString("ImageGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La versión iOS de la App aun no está validada para la App Store.
        /// </summary>
        public static string IOS_VALIDATION_PENDING {
            get {
                return ResourceManager.GetString("IOS_VALIDATION_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A partir de qué versión la App iOS está pendiente de validación por la App Store.
        /// </summary>
        public static string IOS_VALIDATION_PENDING_FROM_VERSION {
            get {
                return ResourceManager.GetString("IOS_VALIDATION_PENDING_FROM_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración iOS.
        /// </summary>
        public static string IOSConfigurationSection {
            get {
                return ResourceManager.GetString("IOSConfigurationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave Api para Notificaciones Push en iOS.
        /// </summary>
        public static string IosPushNotificationsApiKeyDescription {
            get {
                return ResourceManager.GetString("IosPushNotificationsApiKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iOS.
        /// </summary>
        public static string IOSTitle {
            get {
                return ResourceManager.GetString("IOSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está Activo.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Está Activo.
        /// </summary>
        public static string IsInactive {
            get {
                return ResourceManager.GetString("IsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último Acceso.
        /// </summary>
        public static string LastAccess {
            get {
                return ResourceManager.GetString("LastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº/Código Identificación Fiscal.
        /// </summary>
        public static string LegalId {
            get {
                return ResourceManager.GetString("LegalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Nº/Código Identificación Fiscal.
        /// </summary>
        public static string LegalIdType {
            get {
                return ResourceManager.GetString("LegalIdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de {0}.
        /// </summary>
        public static string ListOf {
            get {
                return ResourceManager.GetString("ListOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetList.
        /// </summary>
        public static string ListViewModelAjaxListMethodName {
            get {
                return ResourceManager.GetString("ListViewModelAjaxListMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table-list.
        /// </summary>
        public static string ListViewModelListCssId {
            get {
                return ResourceManager.GetString("ListViewModelListCssId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.C.: &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string LoggedBusinessNameFormula {
            get {
                return ResourceManager.GetString("LoggedBusinessNameFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta: &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string LoggedCustomerNameFormula {
            get {
                return ResourceManager.GetString("LoggedCustomerNameFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fr/Pr: &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string LoggedFranchiseNameFormula {
            get {
                return ResourceManager.GetString("LoggedFranchiseNameFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario: &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string LoggedUserNameFormula {
            get {
                return ResourceManager.GetString("LoggedUserNameFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menú.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Fondo.
        /// </summary>
        public static string MenuBackgroundColor {
            get {
                return ResourceManager.GetString("MenuBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Texto/Iconos Menú.
        /// </summary>
        public static string MenuForegroundColor {
            get {
                return ResourceManager.GetString("MenuForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al desplegar el Menú lateral, ya sea de izquierda o de derecha, muestra un panel con la lista de opciones que componen el menú. Aquí puede elegir el color de fondo de dicho panel y el color de los iconos y el texto de las opciones..
        /// </summary>
        public static string MenuNote {
            get {
                return ResourceManager.GetString("MenuNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meses.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo My Company.
        /// </summary>
        public static string MyLogoCompany {
            get {
                return ResourceManager.GetString("MyLogoCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameFilter.
        /// </summary>
        public static string NameFilterId {
            get {
                return ResourceManager.GetString("NameFilterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameFilterName {
            get {
                return ResourceManager.GetString("NameFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.I.E..
        /// </summary>
        public static string NIE {
            get {
                return ResourceManager.GetString("NIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.I.F..
        /// </summary>
        public static string NIF {
            get {
                return ResourceManager.GetString("NIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [D.C No Especificado].
        /// </summary>
        public static string NoBusinessSelected {
            get {
                return ResourceManager.GetString("NoBusinessSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Sin Cliente].
        /// </summary>
        public static string NoCustomerSelected {
            get {
                return ResourceManager.GetString("NoCustomerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Fr/Pr No Especificado].
        /// </summary>
        public static string NoFranchiseSelected {
            get {
                return ResourceManager.GetString("NoFranchiseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigún Grupo.
        /// </summary>
        public static string NoGroupSelected {
            get {
                return ResourceManager.GetString("NoGroupSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Imagen.
        /// </summary>
        public static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Sin imagen/video).
        /// </summary>
        public static string NoImageOrVideo {
            get {
                return ResourceManager.GetString("NoImageOrVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido seleccionado ninguno.
        /// </summary>
        public static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO IMPLEMENTADO.
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aún No Implementado.
        /// </summary>
        public static string NotImplementedYet {
            get {
                return ResourceManager.GetString("NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No posee los suficientes permisos.
        /// </summary>
        public static string NotPermissions {
            get {
                return ResourceManager.GetString("NotPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No posee los suficientes permisos para realizar esta acción.
        /// </summary>
        public static string NotPermissionsForThisAction {
            get {
                return ResourceManager.GetString("NotPermissionsForThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar....
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string NotSelectedAll {
            get {
                return ResourceManager.GetString("NotSelectedAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Especifica).
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Sin Video).
        /// </summary>
        public static string NoVideo {
            get {
                return ResourceManager.GetString("NoVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración Opciones Por defecto para Ofertas.
        /// </summary>
        public static string OffersDefaultOptionsConfigurationSection {
            get {
                return ResourceManager.GetString("OffersDefaultOptionsConfigurationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Fondo Icono Llamada (Telefono).
        /// </summary>
        public static string OfficeContactIconBackgroundColor {
            get {
                return ResourceManager.GetString("OfficeContactIconBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Icono Llamada (Teléfono).
        /// </summary>
        public static string OfficeContactIconColor {
            get {
                return ResourceManager.GetString("OfficeContactIconColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle &apos;Donde Estamos&apos;.
        /// </summary>
        public static string OfficeDetail {
            get {
                return ResourceManager.GetString("OfficeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Fondo Imagen Superior.
        /// </summary>
        public static string OfficeDetailHeadBackgroundColor {
            get {
                return ResourceManager.GetString("OfficeDetailHeadBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacidad Imagen Superior .
        /// </summary>
        public static string OfficeDetailHeadBackgroundImageOpacity {
            get {
                return ResourceManager.GetString("OfficeDetailHeadBackgroundImageOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En el detalle del contacto, puede mostrarse una imagen representativa de la oficina, delegación, tienda, etc. La opacidad de la imagen, es inversa a la transparencia de la misma, con lo que cuando da un 60% de opacidad, está indicando que la imagen será 40% transparente, por lo que dejará intuir el color de fondo seleccionado..
        /// </summary>
        public static string OfficeDetailHeadBackgroundNote {
            get {
                return ResourceManager.GetString("OfficeDetailHeadBackgroundNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacidad.
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abierto.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bajar Orden.
        /// </summary>
        public static string OrderDown {
            get {
                return ResourceManager.GetString("OrderDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir Orden.
        /// </summary>
        public static string OrderUp {
            get {
                return ResourceManager.GetString("OrderUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retroceder hasta la página {0}.
        /// </summary>
        public static string PaginationButtonBackSeveralPages {
            get {
                return ResourceManager.GetString("PaginationButtonBackSeveralPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avanzar hasta la página {0}.
        /// </summary>
        public static string PaginationButtonGoAheadSeveralPages {
            get {
                return ResourceManager.GetString("PaginationButtonGoAheadSeveralPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Pasaporte.
        /// </summary>
        public static string PASSPORT {
            get {
                return ResourceManager.GetString("PASSPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Teléfono.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Final.
        /// </summary>
        public static string PositionAtTheEnd {
            get {
                return ResourceManager.GetString("PositionAtTheEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Principio.
        /// </summary>
        public static string PositionAtTheInit {
            get {
                return ResourceManager.GetString("PositionAtTheInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Política de Privacidad - Texto por defecto.
        /// </summary>
        public static string PrivacyPolicyLegalNoteDefaultTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyLegalNoteDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Política de Privacidad.
        /// </summary>
        public static string PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las Notificaciones Push han sido enviadas con éxito..
        /// </summary>
        public static string PushNotificationSentSuccessfully {
            get {
                return ResourceManager.GetString("PushNotificationSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea continuar?.
        /// </summary>
        public static string QuestionSureToContinue {
            get {
                return ResourceManager.GetString("QuestionSureToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg. ID.
        /// </summary>
        public static string RegistryId {
            get {
                return ResourceManager.GetString("RegistryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen/Video.
        /// </summary>
        public static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso ha sido cancelado antes de terminar.
        /// </summary>
        public static string ResultCancelled {
            get {
                return ResourceManager.GetString("ResultCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso ha terminado con éxito.
        /// </summary>
        public static string ResultSuccess {
            get {
                return ResourceManager.GetString("ResultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        public static string SatelliteTitle {
            get {
                return ResourceManager.GetString("SatelliteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Todos.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionado.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invertir Selección.
        /// </summary>
        public static string SelectInvert {
            get {
                return ResourceManager.GetString("SelectInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar Título.
        /// </summary>
        public static string ShowTitle {
            get {
                return ResourceManager.GetString("ShowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocas Plateadas.
        /// </summary>
        public static string SilverStones {
            get {
                return ResourceManager.GetString("SilverStones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omitir.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX Code (Internacional).
        /// </summary>
        public static string TAXCODE {
            get {
                return ResourceManager.GetString("TAXCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX ID (Internacional).
        /// </summary>
        public static string TAXID {
            get {
                return ResourceManager.GetString("TAXID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Tierra.
        /// </summary>
        public static string TheEarth {
            get {
                return ResourceManager.GetString("TheEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grosor linea separador título.
        /// </summary>
        public static string TitleSeparatorLineSize {
            get {
                return ResourceManager.GetString("TitleSeparatorLineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir.
        /// </summary>
        public static string ToAdd {
            get {
                return ResourceManager.GetString("ToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir nuevo.
        /// </summary>
        public static string ToAddNew {
            get {
                return ResourceManager.GetString("ToAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string ToCancel {
            get {
                return ResourceManager.GetString("ToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar.
        /// </summary>
        public static string ToChange {
            get {
                return ResourceManager.GetString("ToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        public static string ToChangePassword {
            get {
                return ResourceManager.GetString("ToChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string ToClose {
            get {
                return ResourceManager.GetString("ToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string ToCreate {
            get {
                return ResourceManager.GetString("ToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear y Nueva {0}.
        /// </summary>
        public static string ToCreateAndNewFemale_Format {
            get {
                return ResourceManager.GetString("ToCreateAndNewFemale_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear y Nuevo {0}.
        /// </summary>
        public static string ToCreateAndNewMale_Format {
            get {
                return ResourceManager.GetString("ToCreateAndNewMale_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string ToDelete {
            get {
                return ResourceManager.GetString("ToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivar.
        /// </summary>
        public static string ToDisable {
            get {
                return ResourceManager.GetString("ToDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ToEdit {
            get {
                return ResourceManager.GetString("ToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar.
        /// </summary>
        public static string ToEnable {
            get {
                return ResourceManager.GetString("ToEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivar.
        /// </summary>
        public static string ToFile {
            get {
                return ResourceManager.GetString("ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a Enlace.
        /// </summary>
        public static string ToFollowLink {
            get {
                return ResourceManager.GetString("ToFollowLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a Inicio.
        /// </summary>
        public static string ToGoBackHome {
            get {
                return ResourceManager.GetString("ToGoBackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver al Listado.
        /// </summary>
        public static string ToGoBackToList {
            get {
                return ResourceManager.GetString("ToGoBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver a {0}.
        /// </summary>
        public static string ToGoMainSectionPageOf_Format {
            get {
                return ResourceManager.GetString("ToGoMainSectionPageOf_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminnistrar Secciones.
        /// </summary>
        public static string ToManageCustomerSections {
            get {
                return ResourceManager.GetString("ToManageCustomerSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Secciones.
        /// </summary>
        public static string ToManageMySections {
            get {
                return ResourceManager.GetString("ToManageMySections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Notificaciones Push.
        /// </summary>
        public static string ToNotify {
            get {
                return ResourceManager.GetString("ToNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificar nuevo contenido en Sección.
        /// </summary>
        public static string ToNotifySection {
            get {
                return ResourceManager.GetString("ToNotifySection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        public static string ToOpen {
            get {
                return ResourceManager.GetString("ToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetear (Establecer Por Defecto).
        /// </summary>
        public static string ToResetToDefault {
            get {
                return ResourceManager.GetString("ToResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolver.
        /// </summary>
        public static string ToResolve {
            get {
                return ResourceManager.GetString("ToResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string ToSave {
            get {
                return ResourceManager.GetString("ToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar sin enviar Notificaciones.
        /// </summary>
        public static string ToSaveWithoutSendingPush {
            get {
                return ResourceManager.GetString("ToSaveWithoutSendingPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string ToSelect {
            get {
                return ResourceManager.GetString("ToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Imagen.
        /// </summary>
        public static string ToSelectImage {
            get {
                return ResourceManager.GetString("ToSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Video.
        /// </summary>
        public static string ToSelectVideo {
            get {
                return ResourceManager.GetString("ToSelectVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string ToSend {
            get {
                return ResourceManager.GetString("ToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Cupones.
        /// </summary>
        public static string ToSetCoupons {
            get {
                return ResourceManager.GetString("ToSetCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarchivar.
        /// </summary>
        public static string ToUnfile {
            get {
                return ResourceManager.GetString("ToUnfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Detalles.
        /// </summary>
        public static string ToViewDetails {
            get {
                return ResourceManager.GetString("ToViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe aquí para buscar....
        /// </summary>
        public static string TypeHereForSearching {
            get {
                return ResourceManager.GetString("TypeHereForSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra nungún municipio o localidad que corresponda con el nombre que ha indicado.
        /// </summary>
        public static string UnableToFindCity {
            get {
                return ResourceManager.GetString("UnableToFindCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles de Usuario.
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Number (Unión Europea).
        /// </summary>
        public static string VAT {
            get {
                return ResourceManager.GetString("VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galería de Videos.
        /// </summary>
        public static string VideoGallery {
            get {
                return ResourceManager.GetString("VideoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlace Video #{0}.
        /// </summary>
        public static string VideoLinkTitle {
            get {
                return ResourceManager.GetString("VideoLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Antención!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de letra.
        /// </summary>
        public static string WebFont {
            get {
                return ResourceManager.GetString("WebFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño.
        /// </summary>
        public static string WebFontSize {
            get {
                return ResourceManager.GetString("WebFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estilo.
        /// </summary>
        public static string WebFontStyle {
            get {
                return ResourceManager.GetString("WebFontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Bienvenido!.
        /// </summary>
        public static string Wellcome {
            get {
                return ResourceManager.GetString("Wellcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xatellite - Panel de Control.
        /// </summary>
        public static string XatelliteJumboTitle {
            get {
                return ResourceManager.GetString("XatelliteJumboTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Años.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar al menos uno..
        /// </summary>
        public static string YouMustSelectAtLeatOne {
            get {
                return ResourceManager.GetString("YouMustSelectAtLeatOne", resourceCulture);
            }
        }
    }
}
