//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGE.Cagravol.Presentation.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGE.Cagravol.Presentation.Resources.Common.ErrorResources", typeof(ErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para cambiar la contraseña es necesario que indique la contraseña actual..
        /// </summary>
        public static string ChangePasswordOldPasswordRequired {
            get {
                return ResourceManager.GetString("ChangePasswordOldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido posible crear el usuario &apos;Administrador&apos; para este cliente. El cliente no puede ser creado..
        /// </summary>
        public static string CustomerAdminNotCreated {
            get {
                return ResourceManager.GetString("CustomerAdminNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra el Cliente con el identificador indicado.
        /// </summary>
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra este dispositivo como Registrado!.
        /// </summary>
        public static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido posible guardar los datos, dado que hay errores. Por favor, corrígalos para proceder a guardarlos correctamente.
        /// </summary>
        public static string EditActionNotPossibleErrorExists {
            get {
                return ResourceManager.GetString("EditActionNotPossibleErrorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email indicado para inicio de sesión ya está siendo usado. Debe indicar otra direccion de correo válida.
        /// </summary>
        public static string EmailLoginAlreadyExists {
            get {
                return ResourceManager.GetString("EmailLoginAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las direcciones de correo electrónico no coinciden.
        /// </summary>
        public static string EmailsDontMatch {
            get {
                return ResourceManager.GetString("EmailsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La entidad no existe o es nula.
        /// </summary>
        public static string EntityNullOrDoesNotExist {
            get {
                return ResourceManager.GetString("EntityNullOrDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un Municipio/Localidad para continuar (o puede pulsar en &apos;Cerrar&apos; para cancelar).
        /// </summary>
        public static string ErrorACityShouldBeSelected {
            get {
                return ResourceManager.GetString("ErrorACityShouldBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al enviar un mensaje por Correo Electrónico..
        /// </summary>
        public static string ErrorAtSendingEmailMessage {
            get {
                return ResourceManager.GetString("ErrorAtSendingEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, es necesario volver a registrar el dispositivo..
        /// </summary>
        public static string ErrorGetContentRegisterAgainNeeded {
            get {
                return ResourceManager.GetString("ErrorGetContentRegisterAgainNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha logrado cambiar el estado de esta oferta..
        /// </summary>
        public static string ErrorOfferStateNotAbleToBeChanged {
            get {
                return ResourceManager.GetString("ErrorOfferStateNotAbleToBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al llevar a cabo la acción &apos;{0}&apos;, debido al siguiente motivo: {1}.
        /// </summary>
        public static string ErrorOnActionByCause {
            get {
                return ResourceManager.GetString("ErrorOnActionByCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al intentar crear el registro de {0}. &lt;br/&gt;Ocurrió el siguiente error:&lt;ul&gt; &lt;li&gt;{1}&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string ErrorOnElementCreation {
            get {
                return ResourceManager.GetString("ErrorOnElementCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al consultar la Sección para este elemento. Puede que el identificador no sea correcto..
        /// </summary>
        public static string ErrorOnFetchingSectionForThisItem {
            get {
                return ResourceManager.GetString("ErrorOnFetchingSectionForThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al extraer el archivo de imagen. Asegúrese que el archivo es un formato de imagen correcto. Mensaje de error: {0}.
        /// </summary>
        public static string ErrorOnGettingImageFile {
            get {
                return ResourceManager.GetString("ErrorOnGettingImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al crear el usuario.
        /// </summary>
        public static string ErrorOnUserCreation {
            get {
                return ResourceManager.GetString("ErrorOnUserCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario ya existe en el sistema. No es posible usar el Email indicado..
        /// </summary>
        public static string ErrorOnUserCreation_UserAlreadyExist {
            get {
                return ResourceManager.GetString("ErrorOnUserCreation_UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para enviar todos los enlaces, compruebe lo siguiente: \n - Todos los enlaces deben ser correctos. \n - Todos los videos deben tener Nombre identificativo..
        /// </summary>
        public static string ErrorSendingVideos {
            get {
                return ResourceManager.GetString("ErrorSendingVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &apos;{0}&apos; es obligatorio.
        /// </summary>
        public static string FieldIsMandatory {
            get {
                return ResourceManager.GetString("FieldIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra el archivo.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado del archivo ha cambiado previamente. Por favor, actualice los datos antes de volver a interntarlo..
        /// </summary>
        public static string FileWFStateIsNotInThisStateAnyMore {
            get {
                return ResourceManager.GetString("FileWFStateIsNotInThisStateAnyMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un usuario registrado para esta app con esta misma dirección de email, aunque la contraseña provista no coincide..
        /// </summary>
        public static string FinalUserCustomerIsAlreadyRegisteredAndPasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("FinalUserCustomerIsAlreadyRegisteredAndPasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra ningún usuario existente con ese email para esta app. Por favor, si desea registrar un usuario para esta app con ese Email, use la opcion &apos;Registrar Nuevo Usuario&apos;. Disculpe las molestias..
        /// </summary>
        public static string FinalUserCustomerLogInUserEmailNotFoundForThisApp {
            get {
                return ResourceManager.GetString("FinalUserCustomerLogInUserEmailNotFoundForThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra registro para este dispositivo. Por favor, vuelva a instalar la applicación. Disculpe las molestias..
        /// </summary>
        public static string FinalUserCustomerRegistrationDeviceNotFound {
            get {
                return ResourceManager.GetString("FinalUserCustomerRegistrationDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido posible crear el usuario &apos;Administrador&apos; para esta Franquicia/Promotor. El cliente no puede ser creado..
        /// </summary>
        public static string FranchiseAdminNotCreated {
            get {
                return ResourceManager.GetString("FranchiseAdminNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡No se encuentran secciones disponibles! Por favor, intentelo de nuevo pasados unos segundos. Gracias y disculpe las molestias..
        /// </summary>
        public static string GetInitialContentNoSectionsAvailable {
            get {
                return ResourceManager.GetString("GetInitialContentNoSectionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra el contenido. Puede que este haya sido actualizado. ¡Disculpen la molestia!.
        /// </summary>
        public static string GetItemContentNotFound {
            get {
                return ResourceManager.GetString("GetItemContentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar al menos una imagen..
        /// </summary>
        public static string ImageGalleryAtLeastOneImageSelected {
            get {
                return ResourceManager.GetString("ImageGalleryAtLeastOneImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan sólo puede seleccionar una imagen a la vez..
        /// </summary>
        public static string ImageGalleryOnlyOneImageSelected {
            get {
                return ResourceManager.GetString("ImageGalleryOnlyOneImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La imagen está vacia.
        /// </summary>
        public static string ImageHasNoContent {
            get {
                return ResourceManager.GetString("ImageHasNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El elemento no existe.
        /// </summary>
        public static string ItemDoesNotExist {
            get {
                return ResourceManager.GetString("ItemDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen elementos que mostrar..
        /// </summary>
        public static string ListHasZeroElements {
            get {
                return ResourceManager.GetString("ListHasZeroElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;i class=&quot;fa fa-exclamation-circle&quot;&gt;&lt;/i&gt;&amp;nbsp;&amp;nbsp;No se pudo terminar la acción satisfactoriamente debido a los siguientes errores:&lt;ul&gt;{0}&lt;/ul&gt;&lt;/p&gt;.
        /// </summary>
        public static string ModelStateErrors_Format {
            get {
                return ResourceManager.GetString("ModelStateErrors_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este usuario ya está registrado en el portal de administración. Por razones de seguridad, la contraseña a utilizar debe coincidir con la utilizada en el portal. Todos los intentos de registro para este usuario, serán notificados a dicha dirección de correo como intentos fallidos..
        /// </summary>
        public static string NewFinalUserCustomerIsPortalUserAndPasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("NewFinalUserCustomerIsPortalUserAndPasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las nuevas contraseñas no coinciden.
        /// </summary>
        public static string NewPasswordsDontMatch {
            get {
                return ResourceManager.GetString("NewPasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se econtraron elementos para añadir..
        /// </summary>
        public static string NoItemsToBeAddedFound {
            get {
                return ResourceManager.GetString("NoItemsToBeAddedFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aún no se ha creado ningún Evento..
        /// </summary>
        public static string NoProjectsAlreadyCreated {
            get {
                return ResourceManager.GetString("NoProjectsAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No Implementado Aún.
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear este elemento. Por favor revise la siguiente información:.
        /// </summary>
        public static string OnCreationErrorPleaseReview {
            get {
                return ResourceManager.GetString("OnCreationErrorPleaseReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurió el siguiente error al intentar eliminar el registro: &lt;br/&gt;&lt;ul&gt;&lt;li&gt;{0}&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string OnDeleteError {
            get {
                return ResourceManager.GetString("OnDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se ha eliminado con éxito..
        /// </summary>
        public static string OnDeleteSuccess {
            get {
                return ResourceManager.GetString("OnDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo se pueden subir imágenes (JPG, PNG o GIF).
        /// </summary>
        public static string OnlyImagesAllowed {
            get {
                return ResourceManager.GetString("OnlyImagesAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar una contraseña.
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud de la contraseña debe ser mínimo de {0} carácteres..
        /// </summary>
        public static string PasswordLengthLestThan_Format {
            get {
                return ResourceManager.GetString("PasswordLengthLestThan_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no es válida..
        /// </summary>
        public static string PasswordNotCorrect {
            get {
                return ResourceManager.GetString("PasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña solo admite letras (mayúsculas y minúsculas), números y los siguientes carácteres especiales: $ % @ . , - _ ! ¡ ¿ ? # / \ · ( ).
        /// </summary>
        public static string PaswordAllowOnlyFollowingChars {
            get {
                return ResourceManager.GetString("PaswordAllowOnlyFollowingChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, actualice la página..
        /// </summary>
        public static string PleaseReloadPage {
            get {
                return ResourceManager.GetString("PleaseReloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato del Codigo Postal no es correocto. Debe ser un número entre 5 y 10 dígitos..
        /// </summary>
        public static string PostalCodeFormatError {
            get {
                return ResourceManager.GetString("PostalCodeFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los parametros para establecer una nueva contraseña para la cuenta de usuario no son válidos. Póngase en contacto con su administrador para reestablecer una nueva contraseña de acceso para esta cuenta..
        /// </summary>
        public static string ResetPasswordByEmailNotValidParameters {
            get {
                return ResourceManager.GetString("ResetPasswordByEmailNotValidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sección indicada no existe..
        /// </summary>
        public static string SectionDoesNotBelongToThisCustomer {
            get {
                return ResourceManager.GetString("SectionDoesNotBelongToThisCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede encontrar la sección de la cual desea notificar..
        /// </summary>
        public static string SectionForNotifyDoesNotExist {
            get {
                return ResourceManager.GetString("SectionForNotifyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sesión ha caducado..
        /// </summary>
        public static string SessionHasExpired {
            get {
                return ResourceManager.GetString("SessionHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el directorio temporal para la subida de archivos, dado que no existe o no se encuentra..
        /// </summary>
        public static string TemporaryFolderNotFoundForDeletion {
            get {
                return ResourceManager.GetString("TemporaryFolderNotFoundForDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado.
        /// </summary>
        public static string UnexpectedErrorOcured {
            get {
                return ResourceManager.GetString("UnexpectedErrorOcured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de origen desconocido. Póngase en contacto con el administrador..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos no pudieron ser actializados..
        /// </summary>
        public static string UserCannotBeUpdated {
            get {
                return ResourceManager.GetString("UserCannotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las credenciales de usuario no permiten operar con la cuenta facilitada..
        /// </summary>
        public static string UserCredentialsInvalid {
            get {
                return ResourceManager.GetString("UserCredentialsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los parametros para confirmar la cuenta de usuario no son válidos. Póngase en contacto con su administrador para solucionar la confirmación de esta cuenta..
        /// </summary>
        public static string UserEmailConfirmationNotValidParameters {
            get {
                return ResourceManager.GetString("UserEmailConfirmationNotValidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el usuario para confirmar la cuenta. Puede que el usuario haya sido eliminado. Por favor, póngase en contacto con su administrador para solucionar la confirmación de esta cuenta..
        /// </summary>
        public static string UserEmailConfirmationUserNotFound {
            get {
                return ResourceManager.GetString("UserEmailConfirmationUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no ha confirmado aun a través del enlace enviado por email.&lt;br/&gt;Pulse &lt;a href=&apos;{0}&apos;&gt;aquí&lt;/a&gt; para enviar de nuevo el email de confirmación..
        /// </summary>
        public static string UserEmailNotConfirmed {
            get {
                return ResourceManager.GetString("UserEmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontrado un usuario con el Email indicado..
        /// </summary>
        public static string UserEmailNotFound {
            get {
                return ResourceManager.GetString("UserEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario no tiene privilegios suficientes para realizar esta acción..
        /// </summary>
        public static string UserHasNotAuthorizationToPerformThisAction {
            get {
                return ResourceManager.GetString("UserHasNotAuthorizationToPerformThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta de este Ususario está desactivada..
        /// </summary>
        public static string UserNoActiveAccount {
            get {
                return ResourceManager.GetString("UserNoActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Email o la clave no son válidos..
        /// </summary>
        public static string UserOrEmailNorValid {
            get {
                return ResourceManager.GetString("UserOrEmailNorValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar al menos un video..
        /// </summary>
        public static string VideoGalleryAtLeastOneVideoSelected {
            get {
                return ResourceManager.GetString("VideoGalleryAtLeastOneVideoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan sólo puede seleccionar un video a la vez..
        /// </summary>
        public static string VideoGalleryOnlyOneVideoSelected {
            get {
                return ResourceManager.GetString("VideoGalleryOnlyOneVideoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Atención!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡No se encuentra el proveedor de contenidos para esta app! Por favor, intentelo de nuevo en unos segundos. Gracias y discupe las molestias..
        /// </summary>
        public static string WebApiRegisterDeviceCustomerNotFound {
            get {
                return ResourceManager.GetString("WebApiRegisterDeviceCustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra el Estado en el Workflow..
        /// </summary>
        public static string WFStateNotFound {
            get {
                return ResourceManager.GetString("WFStateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra la Transición en el Workflow..
        /// </summary>
        public static string WFTransitionNotFound {
            get {
                return ResourceManager.GetString("WFTransitionNotFound", resourceCulture);
            }
        }
    }
}
