//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGE.Cagravol.Presentation.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebApiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebApiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGE.Cagravol.Presentation.Resources.Common.WebApiResources", typeof(WebApiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra nigún dispositivo con el identificador indicado..
        /// </summary>
        public static string ErrorDeviceDoesNotExistForThisFinalUser {
            get {
                return ResourceManager.GetString("ErrorDeviceDoesNotExistForThisFinalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string ErrorDeviceDoesNotExistForThisFinalUser_Code {
            get {
                return ResourceManager.GetString("ErrorDeviceDoesNotExistForThisFinalUser_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este dispositivo no se encuentra, ha sido eliminado o bloqueado por alguna razón.  Por favor, pongase en contacto con nosotros en la dirección de correo {0} para solucionarlo. Gracias y perdón por las molestias..
        /// </summary>
        public static string ErrorDeviceNotFound {
            get {
                return ResourceManager.GetString("ErrorDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se encuentra registrado, pero la contraseña no coincide con la contraseña con la que se registró por última vez..
        /// </summary>
        public static string ErrorRegisteredUserPasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("ErrorRegisteredUserPasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string ErrorRegisteredUserPasswordDoesNotMatch_Code {
            get {
                return ResourceManager.GetString("ErrorRegisteredUserPasswordDoesNotMatch_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no se encuentra registrado, o no está vinculado a este dispositivo..
        /// </summary>
        public static string ErrorUserNotBindedForThisDevice {
            get {
                return ResourceManager.GetString("ErrorUserNotBindedForThisDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;¡Hola!&lt;/p&gt;&lt;p&gt;Un nuevo usuario se ha registrado usando un terminal que previamente ha sido registrado por usted. El terminal posee las siguientes características&lt;/p&gt;&lt;p&gt;Sistema Operativo: {0}&lt;/p&gt;&lt;p&gt;Modelo: {1}&lt;/p&gt;&lt;p&gt;Versión: {2}&lt;/p&gt;&lt;p&gt;Atención: Si considera que está siendo víctima de robo o estafa, póngase en contacto con nosotros a través de la dirección de corre electrónico &lt;href=&quot;mailto:{3}&quot;&gt;{3}&lt;/a&gt;&lt;/p&gt;&lt;p&gt;¡Gracias por su atención!&lt;/p&gt;&lt;p&gt;Atte., {4}&lt;/p&gt;&lt;p&gt;&lt;hr/&gt;&lt;/p&gt;&lt;p style=&quot;font-size:80%;&quot;&gt;Nota: Por favor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewUserRegisteredUnsingYourDevice_Body {
            get {
                return ResourceManager.GetString("NewUserRegisteredUnsingYourDevice_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Usuario Registrado en su Dispositivo.
        /// </summary>
        public static string NewUserRegisteredUnsingYourDevice_Subject {
            get {
                return ResourceManager.GetString("NewUserRegisteredUnsingYourDevice_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;¡Hola!&lt;/p&gt;&lt;p&gt;Queremos darte la Bienvenida a nuestra App. Gracias por registrarte como usuario. Al registrarte, podrás acceder a nuevas secciones, acogerte a promociones y descuentos y recibir comunicaciones especialmente pensadas para ti.&lt;/p&gt;&lt;p&gt;En tu sección &quot;Mi Cuenta&quot; puedes encontrar tus datos de registro, así como añadir y/o modificar tus datos personales.&lt;/p&gt;{0}&lt;p&gt;¡Gracias por confiar en nosotros!&lt;/p&gt;&lt;p&gt;Atte., {2}&lt;/p&gt;&lt;p&gt;&lt;hr/&gt;&lt;/p&gt;&lt;p style=&quot;font-size:80%;&quot;&gt;Nota: Por favor, no respondas a este email. S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewUserRegisteredWelcome_Body {
            get {
                return ResourceManager.GetString("NewUserRegisteredWelcome_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Así mismo, te pedimos algunos datos personales. La única razón por la que lo hacemos, es para conocerte mejor y darte una atención más personalizada.&lt;/p&gt;.
        /// </summary>
        public static string NewUserRegisteredWelcome_Body_PMC {
            get {
                return ResourceManager.GetString("NewUserRegisteredWelcome_Body_PMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Bienvenido!.
        /// </summary>
        public static string NewUserRegisteredWelcome_Subject {
            get {
                return ResourceManager.GetString("NewUserRegisteredWelcome_Subject", resourceCulture);
            }
        }
    }
}
